### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by omudongo** [omudongo/-Rethink-Web-Literacy#3]
I'd like to host a small website with a basic logo for use on website, Facebook, Twitter, and newsletter.

I'm picturing a large focus on something that resemble "collaboration".

**Comment by aka4rKO** [comment]
Here's what i have done so far. If you are satisfied with the design i can do the rest and upload it or suggest me on how i can improve it.
![rethink logo](https://user-images.githubusercontent.com/32611549/39881703-4fa0acee-549f-11e8-90d7-39c8ba015a76.JPG)

**Comment by omudongo** [comment]
@aka4rKO thank you so much, perhaps if you could work on the colour (I'd like to adopt some of this bright colours -- better idea here: https://twitter.com/mozillascience and font as well (reasonable size etc) and spacing between fonts need some fixing.

**Comment by 16Suzie** [comment]
Hey ... what do you think of this one 
[RE-THINK WEB LITERACY.pdf](https://github.com/omudongo/-Rethink-Web-Literacy/files/1995107/RE-THINK.WEB.LITERACY.pdf)

**Comment by omudongo** [comment]
@16Suzie this looks more like a brochure, I can use it as well in the future for events if that's okay with you.

**Comment by 16Suzie** [comment]
Received ... Thanks
